services:
  db:
    image: postgres:15-alpine
    container_name: magalabs_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-magalabs_db}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: magalabs_web
    restart: always
    env_file: .env
    environment:
      - DATABASE_URL=postgresql+pg8000://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-magalabs_db}
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - ./MagaLabs_LogPrint_Web/static/uploads:/app/MagaLabs_LogPrint_Web/static/uploads

  deployer:
    build: .
    container_name: magalabs_deployer
    restart: always
    # Sobrescrevemos o comando padrão para rodar o Streamlit
    command: streamlit run "MagaLabs LogPrint.py" --server.port 8501 --server.address 0.0.0.0
    env_file: .env
    ports:
      - "8501:8501"
    depends_on:
      - web

  monitoring:
    build: .
    container_name: magalabs_monitoring
    restart: always
    command: python cds_infra/main.py
    env_file: .env
    environment:
      - DATABASE_URL=postgresql+pg8000://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-magalabs_db}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
